import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    //absolute: "",
    default: "iControl: vc no controle da sua Grana!",
    template: "%s | iControl",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-2 bg-red-200 mb-20">NavBar</header>

        {children}

        <footer className="p-8 mt-80 bg-orange-200">Footer</footer>
      </body>
    </html>
  );
}
